import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {
  normalizeYoutubeUrl,
  resolveContainedPath,
  safeContentPath,
  selectTranscriptLanguage,
  writeFileExclusive,
} from './lib/youtube-transcript-core.mjs';

test('normalizes supported YouTube video URLs and IDs', () => {
  const expected = {
    videoId: '8gg-oJr4dTY',
    canonicalUrl: 'https://www.youtube.com/watch?v=8gg-oJr4dTY',
  };

  assert.deepEqual(normalizeYoutubeUrl('8gg-oJr4dTY'), expected);
  assert.deepEqual(
    normalizeYoutubeUrl('https://youtu.be/8gg-oJr4dTY?t=10'),
    expected,
  );
  assert.deepEqual(
    normalizeYoutubeUrl(
      'https://www.youtube.com/watch?v=8gg-oJr4dTY&feature=shared',
    ),
    expected,
  );
});

test('keeps library and transcript paths inside their fixed roots', () => {
  const libraryRoot = path.join('/repo', 'src/content/youtube');
  const transcriptRoot = path.join('/repo', 'src/content/transcripts');

  assert.equal(
    resolveContainedPath(libraryRoot, 'videos/8gg-oJr4dTY/transcript.md'),
    path.join(libraryRoot, 'videos/8gg-oJr4dTY/transcript.md'),
  );
  assert.equal(
    safeContentPath(transcriptRoot, 'coding-with-agents/example'),
    path.join(transcriptRoot, 'coding-with-agents/example.md'),
  );

  for (const unsafePath of [
    '../escape.md',
    'videos/../../escape.md',
    '/tmp/escape.md',
    'C:\\tmp\\escape.md',
  ]) {
    assert.throws(() => resolveContainedPath(libraryRoot, unsafePath));
    assert.throws(() => resolveContainedPath(transcriptRoot, unsafePath));
  }
});

test('writes non-destructively unless force is explicit', async (t) => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'youtube-core-'));
  t.after(() => rm(tempDir, { recursive: true, force: true }));
  const target = resolveContainedPath(tempDir, 'videos/example/transcript.md');

  const firstWrite = await writeFileExclusive(target, 'first');
  assert.equal(firstWrite.written, true);
  await assert.rejects(
    writeFileExclusive(target, 'second'),
    /Refusing to overwrite existing file/,
  );
  assert.equal(await readFile(target, 'utf8'), 'first');

  const forcedWrite = await writeFileExclusive(target, 'second', {
    force: true,
  });
  assert.equal(forcedWrite.existed, true);
  assert.equal(await readFile(target, 'utf8'), 'second');
});

test('dry-run reports the target without writing it', async (t) => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'youtube-core-'));
  t.after(() => rm(tempDir, { recursive: true, force: true }));
  const target = resolveContainedPath(tempDir, 'videos/example/transcript.md');

  const result = await writeFileExclusive(target, 'not written', {
    dryRun: true,
  });

  assert.deepEqual(result, {
    path: target,
    written: false,
    existed: false,
    dryRun: true,
  });
  await assert.rejects(readFile(target, 'utf8'), { code: 'ENOENT' });
});

test('strict language selection prefers an exact match', () => {
  const selection = selectTranscriptLanguage(
    [
      {
        languageCode: 'it-IT',
        languageName: 'Italian (Italy)',
        isAutoGenerated: true,
      },
      {
        languageCode: 'it',
        languageName: 'Italian',
        isAutoGenerated: false,
      },
    ],
    'it',
    { strict: true },
  );

  assert.equal(selection.status, 'matched');
  assert.equal(selection.language, 'it');
  assert.equal(selection.kind, 'caption');
});

test('strict language selection accepts a regional variant', () => {
  const selection = selectTranscriptLanguage(
    [
      {
        languageCode: 'it-IT',
        languageName: 'Italian (Italy)',
        isAutoGenerated: true,
      },
    ],
    'it',
    { strict: true },
  );

  assert.equal(selection.status, 'matched');
  assert.equal(selection.language, 'it-IT');
  assert.equal(selection.kind, 'auto-generated');
});

test('strict language selection reports requested and available languages', () => {
  const selection = selectTranscriptLanguage(
    [
      {
        languageCode: 'en',
        languageName: 'English',
        isAutoGenerated: false,
      },
      {
        languageCode: 'fr',
        languageName: 'French',
        isAutoGenerated: true,
      },
    ],
    'it',
    { strict: true },
  );

  assert.deepEqual(selection, {
    status: 'unavailable',
    requestedLanguage: 'it',
    availableLanguages: ['en', 'fr'],
  });
});
